<?php
                 include "dbconnect.php";
                 $yget = $_POST["memid"];
                 $yrsql = "select year(dayopencoure) as year,month(dayopencoure) as month,count(dayopencoure) as amount from course WHERE year(dayopencoure) =".$yget." GROUP BY year(dayopencoure),month(dayopencoure);";
                 $retsel = mysql_query($yrsql,$db);
                                echo '<div class="portlet-body">';
        						echo '	<div class="table-scrollable">';
        						echo '		<table class="table table-striped table-hover">';
        						echo '		<thead>';
        						echo '		<tr>';
        						echo '			<th>';
        						echo '				 #';
        						echo '			</th>';
        						echo '			<th>';
        						echo '				 Year';
        						echo '			</th>';
        						echo '			<th>';
        						echo '				 Mounth';
        						echo '			</th>';
        						echo '			<th>';
        						echo '				 Amount';
        						echo '			</th>';
        						echo '		</tr>';
        						echo '		</thead>';
        						echo '		<tbody>';
                                $i = 1;
                                $mon = array();
                                $mon2 = array();
                                $amo = array();
                                $yer = array();
                                $row_num = 0;
                                while($row = mysql_fetch_array($retsel)){
                                    echo '		<tr>';
            						echo '			<th>';
            						echo $i;
            						echo '			</th>';
            						echo '			<th>';
            						echo $yget;//$row['year'];
            						echo '			</th>';
            						echo '			<th>';
            						echo date("F", mktime(0, 0, 0, $row['month'], 10));
            						echo '			</th>';
            						echo '			<th>';
            						echo $row['amount'];
            						echo '			</th>';
            						echo '		</tr>';
                                    $yer[] = $row['year'];
                                    $mon2[] = $row['month'];
                                    $mon[] = date('F', mktime(0, 0, 0, $row['month'], 10));
                                    $amo[] = $row['amount'];
                                    $row_num++; 
                                    $i++;
                                }
        						echo '		</tbody>';
        						echo '		</table>';
        						echo '	</div>';
        						echo '</div>';
                    /*echo '<div class="portlet box blue">';
					echo '	<div class="portlet-title">';
					echo '		<div class="caption">';
					echo '			<i class="fa fa-gift"></i>Bar Chart';
					echo '		</div>';
					echo '		<div class="tools">';
					echo '			<a href="javascript:;" class="collapse">';
					echo '			</a>';
					echo '			<a href="#portlet-config" data-toggle="modal" class="config">';
					echo '			</a>';
					echo '			<a href="javascript:;" class="reload">';
					echo '			</a>';
					echo '			<a href="javascript:;" class="remove">';
					echo '			</a>';
					echo '		</div>';
					echo '	</div>';
					echo '	<div class="portlet-body">';
					echo '		<div id="chart_1_1_legendPlaceholder">';
					echo '		</div>';
					echo '		<div id="yut" class="chart">';
					echo '		</div>';
					echo '	</div>';
					echo '</div>';*/                                     
?>